services:
  backend:
    build:
      -  context: .
      -  dockerfile: docker/Dockerfile
    ports:
      -  8000:8000
    volumes:
      -  .src/:app/src
      -  .tests/:app/tests
    environment:
      -  LOG_LEVEL=INFO
      -  USE_CUDA=false
    healthcheck:
      -  test["CMD","curl","-f","http://localhost:8000/health"]
      -  interval=30s
      -  timeout=10s
      -  retries=3

  frontend:
    build:
      -  context: .frontend/
      -  dockerfile: Dockerfile
    ports:
      -  3000:3000
    volumes:
      -  .frontend/src:app/src
    environment:
      -  BACKEND_URL="http://backend:8000"
    depends_on:
      -  backend

  redis:
    image: redis:alpine
    ports:
      -  6379:6379
    volumes:
      -  redis_data:/data

volumes:
  redis_data:
